stages:

  01_clean:
    cmd: python -m src.stages.01_clean
    deps:
      - src/stages/01_clean.py
      - src/clean
      - data/raw/Dataset_SCO_KVM_MONS_GRC_IZD_DMA_MTK_20250805.csv
      - data/raw/Etagi_secondary_classified_dataset_20250805.csv
      - data/raw/Etagi_secondary_dataset_20250805.csv
      - data/raw/msk_united_geo_market_deals.parquet
    params:
      - 01_clean
    outs:
      - data/interim/01_cleaned.parquet

  02_geocode:
    cmd: python -m src.stages.02_geocode
    deps:
      - data/interim/01_cleaned.parquet
      # - secrets/geocoding/ya_api_keys.csv
      - src/stages/02_geocode.py
      - src/geocode
    params:
      - 02_geocode
    outs:
      - data/interim/02_geocoded.parquet
      - data/cache/geocodes_checkpoint.parquet:
          persist: true

  03_price_discount:
    cmd: python -m src.stages.03_price_discount
    deps:
      - src/stages/03_price_discount.py
      - data/interim/02_geocoded.parquet
      - src/price_discount
    outs:
      - data/interim/03_price_discounted.parquet

  04_wnir:
    cmd: python -m src.stages.04_wnir
    deps:
      - src/stages/04_wnir.py
      - data/interim/03_price_discounted.parquet
      - src/wnir
    outs:
      - data/interim/04_wnir.parquet

  05_administrative_district:
    cmd: python -m src.stages.05_administrative_district
    deps:
      - src/stages/05_administrative_district.py
      - data/interim/04_wnir.parquet
      - src/administrative_district
      - data/complimentary/ao.cpg
      - data/complimentary/ao.dbf
      - data/complimentary/ao.prj
      - data/complimentary/ao.qml
      - data/complimentary/ao.qpj
      - data/complimentary/ao.shp
      - data/complimentary/ao.shx
    outs:
      - data/interim/05_administrative_district.parquet


  06_publish_processed:
    cmd: python -m src.stages.06_publish_processed
    deps:
      - data/interim/05_administrative_district.parquet
      - src/stages/06_publish_processed.py
    outs:
      - data/processed/final.parquet
      - data/processed/final.csv

  06_report:
    cmd: python -m src.stages.06_report
    deps:
      - src/stages/06_report.py
      - src/report
      - data/interim/05_administrative_district.parquet
      
    params:
      - 02_geocode