01_clean:
  area: 
    min: 17.5
    max: 1100
  floor:
    min: -4
    max: 85
  price:
    min: 1_100_000
    max: 7_300_000_000
  build_year:
    min: 1685
    max: null
  address:
    min_len: 12
  common_moscow_point:
    longitude: 37.617644
    latitude: 55.755819

02_geocode:
  geo:
    longitude:
      min: 36.90
      max: 38.05
    latitude:
      min: 55.15
      max: 56.05

03_price_discount:

04_wnir:
  h: 100
  R:
    min: 100
    min-med: 500
    med: 1000
    max-med: 5000
    max: 10000