INTERIM_CLEAN_COLUMNS = {
    "address": "string",
    "latitude": "float32",
    "longitude": "float32",
    "area": "float32",
    "room_count": "UInt8",
    "floor": "Int16",
    "floor_count": "Int16",
    "housing_type": "category",
    "flat_type": "category",
    "ceiling_height": "float32",
    "build_year": "UInt16",
    "balcony": "UInt8",
    "price": "float32",
    "price_per_square_meter": "float32",
    "date": "datetime64[ns]",
    "market_type": "category",
}

CANONICAL_COLUMNS = {
    "address": "string",
    "latitude": "float32",
    "longitude": "float32",
    "area": "float32",
    "room_count": "uint8",
    "floor": "int16",
    "housing_type": "category",
    "flat_type": "category",
    "build_year": "uint16",
    "balcony": "uint8",
    "price": "float32",
    "price_per_square_meter": "float32",
    "date": "datetime64[ns]",
    "market_type": "category",
}
